version: "3"
services:
  app: &base
    build: .
    env_file:
      - ./.env.dev
    command: /bin/sh -c "mkdir -p ./tmp/pids && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
